version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: badminton-frontend
    depends-depends_on:
      - api
    stdin_open: true
    tty: true
  api:
   build:
      context: ./backend
      dockerfile: Dockerfile
   ports:
     - 3080:3080
   container_name: badminton-api
   depends_on:
    - db
# will fix
